### ISSUE TITLE
More tolerant handling of status code 400 errors

### ISSUE THREAD

**Issue by WhoSoup** [AdamSLevy/jsonrpc2#3]
Alright this is definitely something out of the left field. I wanted to get your take on the following:

It is possible but very infrequent that the [factom open node](https://factomd.net/) returns a 400 error with a standard html response. I've already talked to @ilzheev from the open node about making it return a jsonrpc error but unfortunately the error is from cloudflare and out of their control.

The error looks something like this:
`error="json.Unmarshal(<html>\r\n<head><title>400 Bad Request</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>400 Bad Request</h1></center>\r\n<hr><center>cloudflare</center>\r\n</body>\r\n</html>\r\n): invalid character '<' looking for beginning of value"`

The client at the moment treats requests for 200 and 400 the same since it obviously expects a jsonrpc error in case of 400. Do you think it's feasible to add a more tolerant handling of the content for 400 requests only?

Something like:
If the status code is 400 and json fails to unmarshal, send:
`{"jsonrpc": "2.0", "error": {"code": -32099, "message": "custom error: [INSERT HTML RESPONSE HERE]"}, "id": null}`

**Comment by AdamSLevy** [comment]
So one of the issues here is that the JSON-RPC 2.0 spec is not specifically for HTTP. It's agnostic to the transport layer(s). So there is nothing in the specification about HTTP response codes.

In my opinion, the proper way to implement JSON-RPC 2.0 over HTTP is to always use the 200/OK response code regardless of the RPC content. Using the HTTP response code to indicate anything about the response body content, for example using 404/Not Found when a JSON RPC method has something to do with looking something up, is a flawed and messy implementation. If everything about the HTTP transport worked, and it made it to a JSON RPC server, we should expect 200/OK even if we are getting back a JSON RPC 2.0 Error Response. This becomes even more obvious when you consider batch requests, which may contain multiple Responses interspersed with Error Responses.

Reviewing the way the Client.Request is coded I now believe it is actually incorrect:
https://github.com/AdamSLevy/jsonrpc2/blob/3b0dfc9c5f77ea94fb0a5716788110dcf949401a/client.go#L115

This lets the 400 errors through. I believe it does this because of a quirk in factomd's API, where they use a 404 error code but still return an Error Response JSON. I originally wrote this function for factomd and moved it here later when it was so frequently used. I wish they didn't do this and I should probably open up an Issue asking them to change that behavior and always use 200/OK for all JSON RPC responses.

In your case, the client actually *shouldn't* be letting the HTTP 400 Bad Request error through to the next step of unmarshaling of the JSON RPC 2.0 Response. Wrapping this up in a JSON RPC Error is not what I want to do either because now the Client.Request is lying about what happened: pretending it received this Error from the server, but really it created it locally in the Client.Request to communicate that an HTTP error occurred. This is not obvious behavior and obfuscates what happened too much for my tastes.

If this error is intermittent, then you'll want to retry this request on this specific error. Right now the Client.Request only allows distinguishing the JSON RPC Error type from any other error. Information about the http.Response is not available to the caller. 

In the case of factomd's API, which is the biggest use case for this function, but not the specific intention of this package to accommodate, we want the unmarshaling step to occur. I'm sure other JSON RPC 2.0 implementation also make different decisions about HTTP status codes. 

I'd like to find a way to allow both use cases to co-exist, as factomd is probably not the only API that uses HTTP status codes like this.

One way to deal with this is to ignore http status codes entirely and create a new custom error type that stores the http.Response if there is an error unmarshaling into the jsonrpc2.Response.

Something like this:
```
type ErrorResponseUnmarshalJSON struct {
    UnmarshalJSON error
    http.Response
}

func (err ErrorResponseUnmarshalJSON) Error() string{
    return err.UnmarshalJSON.Error()
}
```
If Client.Request returns this, then callers can check for this error after checking for the JSON RPC Error response type.

What do you think about this approach?

**Comment by AdamSLevy** [comment]
It appears since the http.Body will have been read by the time of returning the error a new Reader should be provided in that error type as well.

**Comment by WhoSoup** [comment]
> One way to deal with this is to ignore http status codes entirely and create a new custom error type that stores the http.Response if there is an error unmarshaling into the jsonrpc2.Response.

that's pretty much what i envisioned when i made the issue, so it works for me

**Comment by AdamSLevy** [comment]
@WhoSoup Thanks again for raising this issue. I have now pushed a commit that resolves this issue. See the updated documentation on `Client.Request` and the new `ErrorUnexpectedHTTPResponse`.

https://github.com/AdamSLevy/jsonrpc2/blob/314a45acee07dc87d60425ad639cc2e96e3d61b3/client.go#L78-L105

https://github.com/AdamSLevy/jsonrpc2/blob/314a45acee07dc87d60425ad639cc2e96e3d61b3/client.go#L46-L53

As you can see below, the http.StatusCode is now ignored and the response body is unmarshaled regardless. Unmarshling errors result in the above error type being returned.

https://github.com/AdamSLevy/jsonrpc2/blob/314a45acee07dc87d60425ad639cc2e96e3d61b3/client.go#L147-L162

Since this changes the error handling behavior of `Client.Request` I tagged this as a new release: v14.0.0
