### ISSUE TITLE
Gain access to HTTP request context.

### ISSUE THREAD

**Issue by jmalloc** [AdamSLevy/jsonrpc2#4]
Hi there,

I am looking for a way to access the HTTP request context from within an RPC method. Is there any facility for this, and if not would you be receptive to a PR that added a `ctx` parameter to `MethodFunc`?

/cc @cwx-iggy

**Comment by AdamSLevy** [comment]
Actually I have already implemented exactly this on develop:

For RPC methods:
https://github.com/AdamSLevy/jsonrpc2/blob/9181d6ac9347ddd0b3c503a01ff8f8f2130fb8f5/methods.go#L48-L83

and for Clients:
https://github.com/AdamSLevy/jsonrpc2/blob/9181d6ac9347ddd0b3c503a01ff8f8f2130fb8f5/client.go#L55-L77

I haven't put this in a versioned release yet but at this point I should. In the meantime you can use this code by using the v12 import path everywhere and a replace directive in your go.mod file. But I'm going to go ahead and do a v13 release now so that this is easier to include.

**Comment by jmalloc** [comment]
That's great, thanks!

**Comment by AdamSLevy** [comment]
OK v13.0.0 is pushed. Use the "github.com/AdamSLevy/jsonrpc2/v13" import path.

Cheers!
